try{
    console.log("hello");
    console.log(a);
    console.log("Ending Try");
} catch(err){
    console.log("Handled",err);
}finally{
    console.log("finally");
}

console.log("end");